Proof-of-concept serialization of advanced JSON types, records
dapr/dotnet-sdk pull request #1073
Opened 2023-04-07 20:21 UTC by onionhammer

# Description

Today, complex objects being passed to/from dapr actors must be serializable with DataContractSerializer, which means shotgunning "DataMember" on any primary-constructors (records and C# 8 classes), and difficult workarounds types such as JsonElement.

This PR is a proof-of-concept, as there are areas where this implementation is compromised. A deeper rewrite of Dapr serialization (while still maintaining backwards compatibility) is still necessary.

## Issue reference
- #476
- #679
- #1050

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation

2023-05-23 20:43 UTC, halspang reviewed
Overall this is really nice, thanks taking on this work!

Just a few nitpicks and you'll need to fix the DCO check by signing off on your commit (e.g. `git commit -s`).

2023-05-30 14:01 UTC, onionhammer reviewed
Fixed nits

2023-06-15 05:42 UTC, shivamkm07 requested changes
@onionhammer Can you please rebase this PR to master? It seems to be having cherry-picked master commits. Instead of that, rebasing could be more appropriate.

2023-07-10 17:39 UTC, shivamkm07 commented
> @shivamkm07 My git fu is weak, so please let me know if what I did there helps

@onionhammer All the extra commits are still there. Seems you have cherry-picked master commits to your branch to update. You must not do that. Instead just merge/rebase master to update the changes. To fix the PR, run the following commands:
```
   git checkout add-actor-serialization-options
   git brach temp add-actor-serialization-options // create temp branch to have backup
   git reset --hard upstream/master
   git cherry-pick c0edbd0624dd00d05c9e6eb9869993937c3ccfa7
   git cherry-pick 765204feaaad640c4aafa6ee9056ee122e3cd953
   git cherry-pick e2f94b953b63fc18b3c437508c822e83caf60750
   git push -f origin add-actor-serialization-options
```

Note that above I have used commit hash of the three original commits in the PR. Please ensure these are the ones with the changes you want 
<img width="1270" alt="image" src="https://github.com/dapr/dotnet-sdk/assets/37222089/7d7371c3-49f3-4892-b8a2-5c152e378957">

2023-07-10 18:45 UTC, onionhammer commented
> Seems you have cherry-picked master commits to your branch to update

This is what Github does, built in, no?

2023-07-10 18:58 UTC, onionhammer commented
@shivamkm07 ok, how about now?

2023-07-11 03:52 UTC, shivamkm07 commented
> @shivamkm07 ok, how about now?

Good now. Thanks for updating the PR. 
@halspang the workflows are awaiting for approval. Can you please approve them?

2023-08-01 16:08 UTC, shivamkm07 commented
@onionhammer can you please fix the broken test? One of the integration test is failing

2023-08-01 16:45 UTC, onionhammer commented
@shivamkm07 To be honest, I'm looking at this now, and I'm simply unable to reproduce the error that the CI is getting, any help investigating this would be much appreciated. It looks like some sort of 'timeout' error?

I'm available on discord today if anyone wants to ping me about it.

2023-08-11 13:57 UTC, onionhammer commented
I would love to get some assistance on this one if anyone has the time; I'm available on discord - IM me

2023-08-21 18:49 UTC, onionhammer commented
@shivamkm07 still unable to reproduce this locally. Is there a way to run the github actions locally (in a way that works?) Act doesnt seem to work for this project.

2023-08-22 13:14 UTC, shivamkm07 commented
> @shivamkm07 still unable to reproduce any issues with the tests locally. Is there a way to run the github actions locally (in a way that works?) Act doesnt seem to work for this project.

Tests seem to pass after the changes. Thanks for the fix. Please also fix the DCO.

2023-09-05 19:16 UTC, halspang approved these changes

2023-09-05 19:16 UTC, merged

2024-02-19 13:10 UTC, darraghjones commented
https://github.com/dapr/dotnet-sdk/blob/master/daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-serialization.md should probably be updated

2024-10-18 08:24 UTC, WhitWaldo commented
> https://github.com/dapr/dotnet-sdk/blob/master/daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-serialization.md should probably be updated

Following up here - just merged a PR that'll deploy with 1.15 in which I've addressed the JSON serialization alongside the existing Data Contract serialization.