Updates Dapr to 1.12 in GitHub actions itest
dapr/dotnet-sdk pull request #1185
Opened 2023-11-13 13:48 UTC by JoshVanL

2023-11-13 23:19 UTC, halspang commented on .github/workflows/itests.yml
> +      DAPR_REF: '2149fca96cdf11627c387bda26dcc027d1c47354'
The Dapr ref set's a specific commit and is redundant to the 1.12 flag. I'd prefer we just set 1.12 and leave that blank.

2023-11-13 23:19 UTC, halspang requested changes
Let's remove the commit ref as that's for updating the dapr version for a new feature (mid release).

2023-11-15 18:30 UTC, halspang commented
Yeah, that sure does. @RyanLettieri, can you take a look at this workflow failure?

2023-11-15 18:50 UTC, RyanLettieri commented
@JoshVanL The error looks like it is coming from an assert statement after we purge an instance and attempt to get the workflow instance back. The current statement we use to check for this is the following:
`ex.InnerException.Message.Should().Contain("No such instance exists", $"Instance {instanceId} was not correctly purged");`

Due to Should().Contain() being case-sensitive, the error is probably coming from a change in the capitalization of the error message. From the error logs:

> Error: Dapr.E2E.Test.E2ETests.TestWorkflows: Expected string "Status(StatusCode="NotFound", Detail="unable to find workflow with the provided instance ID: testInstanceId%!(EXTRA *fmt.wrapError=Failed to fetch orchestration metadata: no such instance exists)")" to contain "No such instance exists" because Instance testInstanceId was not correctly purged.

It appears we check for a capital N on the error whereas the error in 1.12 seems to use a lower-case N. I'd recommend changing that line and re-running the test

2023-11-15 19:22 UTC, JoshVanL commented
Thanks @RyanLettieri! Really appreciate the detailed breakdown- I'm still getting used to dotnet so thanks for the help.

2023-11-29 00:28 UTC, halspang approved these changes

2023-11-29 00:28 UTC, merged