Added ActorReference creation from the actor base class informations
dapr/dotnet-sdk pull request #1277
Opened 2024-04-29 21:45 UTC by m3nax

# Description

Handled the case where you want to create an ActorReference inside the actor implementation from the information in the Actor base class. Added missing test for ActoreReference.Get method.

Example:
``` CSharp
public interface ITestActor: IActor
{
  Task TestMethod();
}

public class TestActor: Actor, ITestActor
{
  public TestActor(ActorHost host)
    : base(host)
  {
  }

  public Task TestMethod()
  {
    // An ArgumentOutOfRangeException is thrown because the Actor 
    // parameter cannot be cast to the IActorProxy interface.
    // in this case the ActorReference must be created based on the information 
    // contained in the base class Actor
    var reference = ActorReference.Get(this);
  }
}
```

## Issue reference

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation

2024-05-22 06:18 UTC, m3nax commented
@philliphoff Another transient error seems to have appeared in actions.

Is there a command that can be given to re-execute actions? 
Like `\assign` to assign issues

Recorded error in `integration-test / run integration tests (6.0) (pull_request)`
```
Error: Dapr.E2E.Test.GrpcProxyTests.TestGrpcProxyStreamingBroadcast: Grpc.Core.RpcException : Status(StatusCode="Unavailable", Detail="connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:37149: connect: connection refused"")
```

2024-06-05 22:50 UTC, philliphoff requested changes
Looks good to me, @m3nax. Just need to resolve the merge conflict and it can be committed.

2024-06-06 06:33 UTC, m3nax commented
@philliphoff Done

2024-06-26 17:29 UTC, m3nax commented
@philliphoff can be included in [v1.14](https://github.com/dapr/dotnet-sdk/milestone/19) milestone?

2024-06-26 21:37 UTC, philliphoff approved these changes
LGTM

2024-06-26 21:37 UTC, merged