Provide the ability to Mock WorkflowActivityContext
dapr/dotnet-sdk pull request #1358
Opened 2024-10-10 17:36 UTC by siri-varma

# Description

Made the WorkflowActivityContext abstract.
Created DaprWorkflowActivityContext  and made it inherit from WorkflowActivityContext 

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[1200]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [X] Created/updated tests
* [X] Extended the documentation

2024-10-10 19:39 UTC, WhitWaldo commented
@siri-varma It looks like the DCO check failed. 

Could you please make sure each of your commits are signed?

2024-12-11 21:34 UTC, WhitWaldo commented
@siri-varma Looks like we've got several build errors regarding nullability. If you can fix those, I'd appreciate it!

2024-12-27 19:15 UTC, siri-varma commented
@WhitWaldo let me know if anything else is needed on this PR. Thank you

2024-12-27 23:27 UTC, WhitWaldo requested changes
Just a couple of nits and we're good here.

2024-12-28 13:28 UTC, siri-varma commented on src/Dapr.Workflow/WorkflowActivityContext.cs
> +        /// Gets the unique ID of thcurrent workflow instance.
@WhitWaldo done resolved

2024-12-28 19:04 UTC, WhitWaldo approved these changes

2024-12-28 19:24 UTC, merged

2024-12-28 19:24 UTC, WhitWaldo commented
Thank you very much for your contribution @siri-varma !

2025-01-10 16:12 UTC, marcduiker commented
@holopin-bot @siri-varma Thanks so much this contribution! 🚀