Add more unit tests for InvokeBindingAsync
dapr/dotnet-sdk pull request #639
Opened 2021-03-23 20:05 UTC by mukundansundar

# Description

Added two unit tests: 
1. Invoke Binding Async with  custom data and validate payload deserialization
2. Invoke Binding Async with  Null custom data and validate payload deserialization

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #550 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation

2021-03-24 00:17 UTC, vinayada1 commented on test/Dapr.Client.Test/InvokeBindingApiTest.cs
> +        public async Task InvokeBindingAsync_WithCustomNullPayload_ValidateRequestResponse()
nit: WithCustomNullPayload => withnullpayload.

2021-03-24 00:18 UTC, vinayada1 submitted a review, later dismissed
Left a nit comment

2021-03-24 01:14 UTC, mukundansundar commented on test/Dapr.Client.Test/InvokeBindingApiTest.cs
> +        public async Task InvokeBindingAsync_WithCustomNullPayload_ValidateRequestResponse()
done

2021-03-24 01:56 UTC, rynowak commented on test/Dapr.Client.Test/InvokeBindingApiTest.cs
> +            envelope.Metadata.Count.Should().Be(2);
Should this also verify the binding operation? (`create`)

Should this also verify the body of the request? It's checking the response, but not the request.

2021-03-24 01:56 UTC, rynowak commented on test/Dapr.Client.Test/InvokeBindingApiTest.cs
> +                return await daprClient.InvokeBindingAsync<InvokeRequest, Widget>("test","create", data, metadata);
missing space after comma

2021-03-24 01:57 UTC, rynowak commented on test/Dapr.Client.Test/InvokeBindingApiTest.cs
> +            envelope.Metadata.Count.Should().Be(0);
Would be good to also validate the operation (`create`)

2021-04-30 20:39 UTC, rynowak requested changes
Waiting on updates here

2021-06-06 20:42 UTC, rynowak commented
@mukundansundar - do you plan to finish this?

2021-09-16 22:37 UTC, rynowak commented
Closing in favor of #751

2021-09-16 22:37 UTC, closed without merging