Added actor method exception details docs
dapr/dotnet-sdk pull request #950
Opened 2022-09-14 05:58 UTC by amulyavarote

Signed-off-by: Amulya Varote <amulyavarote@microsoft.com>

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #NA

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2022-09-14 17:42 UTC, hhunter-ms requested changes
quick grammar pass

2022-09-14 17:42 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-client.md
> +### Actor Method Invocation Exception Details.
```suggestion
### Actor method invocation exception details
```

2022-09-14 17:42 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-actors/dotnet-actors-client.md
> +The actor method invocation exception details like method name, line number, exception type and UUID is surfaced to the caller so that there is an entry point to track down the issue. These details a
```suggestion
The actor method invocation exception details are surfaced to the caller and the callee, providing an entry point to track down the issue. Exception details include:

 - Method name
 - Line number
 - Exception type
 - UUID 
 
You use the UUID to match the exception on the caller and callee side. Below is an example of exception details:
```

2022-09-14 17:51 UTC, hhunter-ms approved these changes
lgtm!

2022-09-16 00:39 UTC, halspang approved these changes

2022-09-16 00:40 UTC, merged